### ISSUE TITLE
[Errno 2] No such file or directory: '../runs/mobilenetv3large_v1.50.pt'

### ISSUE THREAD

**Issue by OSSome01** [nmhaddad/semantic-segmentation#2]
The trained mobilenetv3large_v1.50.pt model is not present in the repo. Do I have to get it from somewhere else? If yes, please point me from where I could get it.

I'm getting this error when i try to run "test.py"

**Comment by nmhaddad** [comment]
@OSSome01 I added a link in the readme to a Google drive with access to a pretrained model. It's also here https://drive.google.com/drive/folders/1Gmk8vOF9qBNMg3-TEL-st6KWieB4Af5e?usp=sharing
